-- USE THIS STATMENT TO
-- ADD COLUMNS OR CONSTRAINTS TO AN EXISTING TABLE
ALTER TABLE Examples.Widget
	ADD NotNullableColumn int NOT NULL
		CONSTRAINT DFLT_COLUMN DEFAULT(100) -- ALWAYS SET A DEFAULT VALUE

--INSERT INTO Examples.WIDGET values ('1', 'NAME', 'PRICE', 0)
--ALTER TABLE Examples.Widget DROP COLUMN NotNullableColumn
SELECT * FROM Examples.Widget